jokes = [
    {'id':0, 'joke':'Error 0094782: No se detecta ningún teclado.', 'punchline':'Pulse una tecla para continuar.'},
    {'id':1, 'joke': 'Doctor, doctor, no sé lo que me pasa que cada vez que tomo café me duele el ojo derecho.', 'punchline': '¿Has probado a sacar la cuchara de la taza?'},
    {'id':2, 'joke': '¿Cuántos técnicos informáticos de Microsoft hacen falta para cambiar una bombilla?.', 'punchline':'Ninguno, es un problema de Hardware.'},
    {'id':3, 'joke': 'Buenos días, me gustaría alquilar "Batman Forever".','punchline':'No es posible, tiene que devolverla tomorrow.'}, 
    {'id':4, 'joke': 'Si somos vecinos, y yo vivo abajo y tu vives arriba…', 'punchline':'¿podríamos decir que «techo de menos»?'}, 
    {'id':5, 'joke': '¿Por qué las focas del circo miran siempre hacia arriba?', 'punchline':'Porque arriba están los focos.'},
    {'id':6, 'joke': '¡Camarero! Este filete tiene muchos nervios.', 'punchline':'Normal, es la primera vez que se lo comen.'},
    {'id':7, 'joke': 'Oye, ¿cuál es tu plato favorito y por qué?','punchline':'Pues el hondo, porque cabe más comida…'},
    {'id':8, 'joke': '¿Por qué los diabéticos no pueden vengarse?','punchline': 'Porque la venganza es dulce'}, 
    {'id':9, 'joke': 'Tengo tres llamadas perdidas de mi oftalmólogo...', 'punchline':'El de ver me llama.'},
    {'id':10, 'joke': '¿Por qué estás hablando con esas zapatillas?', 'punchline':'Porque pone "converse"'}, 
    {'id':11, 'joke': 'Me da un café con leche corto.', 'punchline':'Se me ha roto la máquina, cambio.'}, 
    {'id':12, 'joke': 'Mamá, mamá, los spaghetti se están pegando.','punchline':'Déjalos que se maten'},
    {'id':13, 'joke': 'Jesús, ¿qué tal la última cena? ¿Salió cara?','punchline': 'No, salio cruz'}, 
    {'id':14, 'joke': '¿Cuál es el coche favorito de un fotógrafo?', 'punchline':'El Ford Focus.'},
    {'id':15, 'joke': 'Ayer me caí y pensé que me había roto el peroné…', 'punchline':'¡Peronó!'}, 
    {'id':16, 'joke': '¿Cómo se llama el primo vegano de Bruce Lee?', 'punchline':'Broco Lee.'},
    {'id':17, 'joke': '¿Cómo se llama el campeón de buceo japonés?', 'punchline':'Tokofondo.' },
    {'id':18, 'joke': '¿Sabes que le dice un .gif a un .jpg?', 'punchline':'¡Anímate hombre!'},
    {'id':19, 'joke': '¿Cómo se despiden los químicos?','punchline': 'Ácido un placer.'},
    {'id':20, 'joke': '¿Cómo se dice no en Sudáfrica?','punchline':'Mopongo.'},
    {'id':21, 'joke': '¿Cómo se llama hacer dieta en chino? ','punchline':'Kita Kilito.'},
    {'id':22, 'joke': '¿Cuál es el café más peligroso del mundo?','punchline':'El ex-preso'},
    {'id':23, 'joke': 'Soy Rosa.','punchline':'Ah, perdóname, es que soy daltónico.'},
    {'id':24, 'joke': '¿Te gusta el progressive house?','punchline':'Cada vez mas...'},   
    {'id':25, 'joke': 'Me cayo mal la comida', 'punchline':'Entonces no le hables y ya...'}, 
    {'id':26, 'joke': '¿Qué coche usa Papá Noel?','punchline': 'Un renol'}, 
    {'id':27, 'joke': '¿Cuál es la fruta más divertida?', 'punchline':'La naranja ja ja'},
    {'id':28, 'joke': '¿Dónde cuelga Superman su supercapa?', 'punchline':'En superchero'}, 
    {'id':29, 'joke': '¿Cómo se dice "espejo" en chino?','punchline': 'Aitoiyo'}, 
    {'id':30, 'joke': 'Doctor, soy asmático, ¿es grave?', 'punchline':'No, es esdrújula….'},
]
